CREATE TABLE "achievements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "achievements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" varchar(50) NOT NULL,
	"titel" varchar(100) NOT NULL,
	"beschreibung" text,
	"icon" varchar(50),
	CONSTRAINT "achievements_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "answer_options" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "answer_options_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"question_id" integer NOT NULL,
	"text" varchar(100) NOT NULL,
	"ist_richtig" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE "duel_answers" (
	"duel_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"question_id" integer NOT NULL,
	"answer_option_id" integer,
	"antwortzeit_ms" integer,
	"ist_richtig" boolean NOT NULL,
	CONSTRAINT "duel_answers_duel_id_user_id_question_id_pk" PRIMARY KEY("duel_id","user_id","question_id")
);
--> statement-breakpoint
CREATE TABLE "duel_questions" (
	"duel_id" integer NOT NULL,
	"question_id" integer NOT NULL,
	"reihenfolge" smallint NOT NULL,
	CONSTRAINT "duel_questions_duel_id_reihenfolge_pk" PRIMARY KEY("duel_id","reihenfolge"),
	CONSTRAINT "duel_questions_reihenfolge_check" CHECK ("duel_questions"."reihenfolge" between 1 and 6)
);
--> statement-breakpoint
CREATE TABLE "duels" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "duels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spieler_a_id" integer NOT NULL,
	"spieler_b_id" integer NOT NULL,
	"kategorie" varchar(20) NOT NULL,
	"status" varchar(20) DEFAULT 'wartet_a' NOT NULL,
	"erstellt_at" timestamp with time zone DEFAULT now() NOT NULL,
	"abgeschlossen_at" timestamp with time zone,
	"gewertet_at" timestamp with time zone,
	CONSTRAINT "duels_kategorie_check" CHECK ("duels"."kategorie" in ('kulturen', 'schaedlinge', 'krankheiten', 'wissen', 'gemischt')),
	CONSTRAINT "duels_status_check" CHECK ("duels"."status" in ('wartet_a', 'wartet_b', 'abgeschlossen')),
	CONSTRAINT "duels_verschiedene_spieler_check" CHECK ("duels"."spieler_a_id" <> "duels"."spieler_b_id")
);
--> statement-breakpoint
CREATE TABLE "friendships" (
	"user_id" integer NOT NULL,
	"friend_id" integer NOT NULL,
	"status" varchar(20) DEFAULT 'angefragt' NOT NULL,
	"erstellt_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "friendships_user_id_friend_id_pk" PRIMARY KEY("user_id","friend_id"),
	CONSTRAINT "friendships_status_check" CHECK ("friendships"."status" in ('angefragt', 'bestaetigt')),
	CONSTRAINT "friendships_nicht_selbst_check" CHECK ("friendships"."user_id" <> "friendships"."friend_id")
);
--> statement-breakpoint
CREATE TABLE "questions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kategorie" varchar(20) NOT NULL,
	"typ" varchar(10) NOT NULL,
	"frage_text" text NOT NULL,
	"bild_url" text,
	"bild_quelle" text,
	"schwierigkeit" smallint DEFAULT 1 NOT NULL,
	"erklaerung" text,
	"status" varchar(20) DEFAULT 'freigegeben' NOT NULL,
	"eingereicht_von" integer,
	CONSTRAINT "questions_kategorie_check" CHECK ("questions"."kategorie" in ('kulturen', 'schaedlinge', 'krankheiten', 'wissen')),
	CONSTRAINT "questions_typ_check" CHECK ("questions"."typ" in ('bild', 'text')),
	CONSTRAINT "questions_status_check" CHECK ("questions"."status" in ('entwurf', 'eingereicht', 'freigegeben', 'abgelehnt')),
	CONSTRAINT "questions_schwierigkeit_check" CHECK ("questions"."schwierigkeit" between 1 and 5),
	CONSTRAINT "questions_bild_check" CHECK ("questions"."typ" <> 'bild' or "questions"."bild_url" is not null)
);
--> statement-breakpoint
CREATE TABLE "ratings" (
	"user_id" integer NOT NULL,
	"kategorie" varchar(20) NOT NULL,
	"saison" integer NOT NULL,
	"rating" integer DEFAULT 1000 NOT NULL,
	"duelle_gespielt" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "ratings_user_id_kategorie_saison_pk" PRIMARY KEY("user_id","kategorie","saison"),
	CONSTRAINT "ratings_kategorie_check" CHECK ("ratings"."kategorie" in ('gesamt', 'kulturen', 'schaedlinge', 'krankheiten', 'wissen'))
);
--> statement-breakpoint
CREATE TABLE "user_achievements" (
	"user_id" integer NOT NULL,
	"achievement_id" integer NOT NULL,
	"erreicht_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_achievements_user_id_achievement_id_pk" PRIMARY KEY("user_id","achievement_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(50) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
ALTER TABLE "answer_options" ADD CONSTRAINT "answer_options_question_id_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duel_answers" ADD CONSTRAINT "duel_answers_duel_id_duels_id_fk" FOREIGN KEY ("duel_id") REFERENCES "public"."duels"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duel_answers" ADD CONSTRAINT "duel_answers_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duel_answers" ADD CONSTRAINT "duel_answers_question_id_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duel_answers" ADD CONSTRAINT "duel_answers_answer_option_id_answer_options_id_fk" FOREIGN KEY ("answer_option_id") REFERENCES "public"."answer_options"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duel_questions" ADD CONSTRAINT "duel_questions_duel_id_duels_id_fk" FOREIGN KEY ("duel_id") REFERENCES "public"."duels"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duel_questions" ADD CONSTRAINT "duel_questions_question_id_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duels" ADD CONSTRAINT "duels_spieler_a_id_users_id_fk" FOREIGN KEY ("spieler_a_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duels" ADD CONSTRAINT "duels_spieler_b_id_users_id_fk" FOREIGN KEY ("spieler_b_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "friendships" ADD CONSTRAINT "friendships_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "friendships" ADD CONSTRAINT "friendships_friend_id_users_id_fk" FOREIGN KEY ("friend_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questions" ADD CONSTRAINT "questions_eingereicht_von_users_id_fk" FOREIGN KEY ("eingereicht_von") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_achievement_id_achievements_id_fk" FOREIGN KEY ("achievement_id") REFERENCES "public"."achievements"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "answer_options_question_idx" ON "answer_options" USING btree ("question_id");--> statement-breakpoint
CREATE UNIQUE INDEX "answer_options_eine_richtige_idx" ON "answer_options" USING btree ("question_id") WHERE "answer_options"."ist_richtig";--> statement-breakpoint
CREATE INDEX "duel_answers_user_idx" ON "duel_answers" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "duel_questions_frage_idx" ON "duel_questions" USING btree ("duel_id","question_id");--> statement-breakpoint
CREATE INDEX "duels_spieler_a_idx" ON "duels" USING btree ("spieler_a_id","status");--> statement-breakpoint
CREATE INDEX "duels_spieler_b_idx" ON "duels" USING btree ("spieler_b_id","status");--> statement-breakpoint
CREATE INDEX "friendships_friend_idx" ON "friendships" USING btree ("friend_id");--> statement-breakpoint
CREATE INDEX "questions_kategorie_status_idx" ON "questions" USING btree ("kategorie","status");--> statement-breakpoint
CREATE INDEX "ratings_bestenliste_idx" ON "ratings" USING btree ("kategorie","saison","rating" DESC NULLS LAST);