CREATE TABLE "frage_meldungen" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "frage_meldungen_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"question_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"grund" varchar(20) NOT NULL,
	"kommentar" text,
	"status" varchar(20) DEFAULT 'offen' NOT NULL,
	"erstellt_at" timestamp with time zone DEFAULT now() NOT NULL,
	"abgeschlossen_at" timestamp with time zone,
	"abgeschlossen_von" integer,
	CONSTRAINT "frage_meldungen_grund_check" CHECK ("frage_meldungen"."grund" in ('antwort_falsch', 'frage_unklar', 'sonstiges')),
	CONSTRAINT "frage_meldungen_status_check" CHECK ("frage_meldungen"."status" in ('offen', 'erledigt', 'verworfen'))
);
--> statement-breakpoint
ALTER TABLE "frage_meldungen" ADD CONSTRAINT "frage_meldungen_question_id_questions_id_fk" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "frage_meldungen" ADD CONSTRAINT "frage_meldungen_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "frage_meldungen" ADD CONSTRAINT "frage_meldungen_abgeschlossen_von_users_id_fk" FOREIGN KEY ("abgeschlossen_von") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "frage_meldungen_offen_idx" ON "frage_meldungen" USING btree ("question_id","user_id") WHERE "frage_meldungen"."status" = 'offen';--> statement-breakpoint
CREATE INDEX "frage_meldungen_user_idx" ON "frage_meldungen" USING btree ("user_id","erstellt_at");